version: '3.9'

services:
  site-futeletrica:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: site-futeletrica
    environment:
      - ALLOWED_HOSTS=futeletrica.com.br,www.futeletrica.com.br
      - VIRTUAL_HOST=futeletrica.com.br,www.futeletrica.com.br
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=futeletrica.com.br,www.futeletrica.com.br
      - LETSENCRYPT_EMAIL=futeletrica2013@gmail.com

networks:
  default:
    external:
      name: nginx-proxy
