# Generated by Django 5.2.6 on 2026-05-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_grupos_aberta', models.BooleanField(default=True)),
                ('prazo_fase_grupos', models.DateTimeField(blank=True, null=True)),
                ('fase_16avos_aberta', models.BooleanField(default=False)),
                ('fase_oitavas_aberta', models.BooleanField(default=False)),
                ('fase_quartas_aberta', models.BooleanField(default=False)),
                ('fase_semi_aberta', models.BooleanField(default=False)),
                ('fase_terceiro_aberta', models.BooleanField(default=False)),
                ('fase_final_aberta', models.BooleanField(default=False)),
                ('palpites_publicos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração do Bolão',
                'verbose_name_plural': 'Configurações do Bolão',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1, unique=True)),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('pin_hash', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('bandeira_emoji', models.CharField(blank=True, max_length=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecoes', to='bolao.grupo')),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
                'ordering': ['grupo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('rodada', models.PositiveSmallIntegerField(default=1)),
                ('fase', models.CharField(default='grupos', max_length=20)),
                ('gols_casa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_fora', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='bolao.grupo')),
                ('selecao_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='bolao.selecao')),
                ('selecao_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='bolao.selecao')),
            ],
            options={
                'verbose_name': 'Jogo',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_fora', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pontos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='bolao.jogo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='bolao.participante')),
            ],
            options={
                'ordering': ['jogo__data_hora'],
                'unique_together': {('participante', 'jogo')},
            },
        ),
        migrations.CreateModel(
            name='PalpiteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('campeao', 'Campeão'), ('vice', 'Vice-Campeão'), ('terceiro', 'Terceiro Colocado'), ('pior', 'Pior Seleção')], max_length=10)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites_extras', to='bolao.participante')),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.selecao')),
            ],
            options={
                'unique_together': {('participante', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='PalpiteClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.grupo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites_classificacao', to='bolao.participante')),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.selecao')),
            ],
            options={
                'ordering': ['grupo', 'posicao'],
                'unique_together': {('participante', 'grupo', 'posicao')},
            },
        ),
    ]
