# Generated by Django 5.2.6 on 2026-05-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jogo',
            name='numero_jogo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='fase',
            field=models.CharField(choices=[('grupos', 'Fase de Grupos'), ('16avos', '16-avos de Final'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinais'), ('terceiro', 'Disputa 3º Lugar'), ('final', 'Final')], default='grupos', max_length=20),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='bolao.grupo'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='selecao_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='bolao.selecao'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='selecao_fora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='bolao.selecao'),
        ),
    ]
